// Each module maps directly to a backend REST resource.
// `fields` drives both the table columns and the create/edit form.
// type: text | number | date | textarea | select

export const modules = [
  {
    key: 'students',
    title: 'Students',
    icon: 'students',
    endpoint: '/students',
    listLabel: (row) => `${row.firstName || ''} ${row.lastName || ''}`.trim() || row.admissionNumber,
    fields: [
      { name: 'admissionNumber', label: 'Admission No.', type: 'text', required: true },
      { name: 'firstName', label: 'First Name', type: 'text', required: true },
      { name: 'lastName', label: 'Last Name', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'select', options: ['MALE', 'FEMALE', 'OTHER'] },
      { name: 'dateOfBirth', label: 'Date of Birth', type: 'date' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'parentName', label: 'Parent Name', type: 'text' },
      { name: 'parentPhone', label: 'Parent Phone', type: 'text' },
      { name: 'className', label: 'Class', type: 'text' },
      { name: 'section', label: 'Section', type: 'text' },
    ],
    columns: ['admissionNumber', 'firstName', 'lastName', 'className', 'section', 'phone'],
  },
  {
    key: 'teachers',
    title: 'Teachers',
    icon: 'teachers',
    endpoint: '/teachers',
    listLabel: (row) => row.name || row.employeeId,
    fields: [
      { name: 'employeeId', label: 'Employee ID', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'qualification', label: 'Qualification', type: 'text' },
      { name: 'joiningDate', label: 'Joining Date', type: 'date' },
    ],
    columns: ['employeeId', 'name', 'subject', 'qualification', 'phone'],
  },
  {
    key: 'classes',
    title: 'Classes',
    icon: 'classes',
    endpoint: '/classes',
    listLabel: (row) => `${row.className || ''} ${row.section || ''}`.trim(),
    fields: [
      { name: 'className', label: 'Class Name', type: 'text', required: true },
      { name: 'section', label: 'Section', type: 'text' },
      { name: 'academicYear', label: 'Academic Year', type: 'text' },
      { name: 'classTeacherId', label: 'Class Teacher ID', type: 'number' },
    ],
    columns: ['className', 'section', 'academicYear', 'classTeacherId'],
  },
  {
    key: 'subjects',
    title: 'Subjects',
    icon: 'subjects',
    endpoint: '/subjects',
    listLabel: (row) => row.name,
    fields: [
      { name: 'name', label: 'Subject Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text' },
      { name: 'maxMarks', label: 'Max Marks', type: 'number' },
      { name: 'teacherId', label: 'Teacher ID', type: 'number' },
      { name: 'className', label: 'Class', type: 'text' },
    ],
    columns: ['name', 'code', 'maxMarks', 'className', 'teacherId'],
  },
  {
    key: 'attendance',
    title: 'Attendance',
    icon: 'attendance',
    endpoint: '/attendance',
    listLabel: (row) => `Student #${row.studentId} — ${row.date}`,
    fields: [
      { name: 'studentId', label: 'Student ID', type: 'number', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
      { name: 'status', label: 'Status', type: 'select', options: ['PRESENT', 'ABSENT', 'LATE'] },
    ],
    columns: ['studentId', 'date', 'status'],
  },
  {
    key: 'exams',
    title: 'Exams',
    icon: 'exams',
    endpoint: '/exams',
    listLabel: (row) => row.name,
    fields: [
      { name: 'name', label: 'Exam Name', type: 'text', required: true },
      { name: 'examDate', label: 'Exam Date', type: 'date' },
      { name: 'className', label: 'Class', type: 'text' },
      { name: 'academicYear', label: 'Academic Year', type: 'text' },
    ],
    columns: ['name', 'examDate', 'className', 'academicYear'],
  },
  {
    key: 'results',
    title: 'Results',
    icon: 'results',
    endpoint: '/results',
    listLabel: (row) => `Student #${row.studentId} — ${row.examName || ''}`,
    fields: [
      { name: 'studentId', label: 'Student ID', type: 'number', required: true },
      { name: 'subjectId', label: 'Subject ID', type: 'number' },
      { name: 'examName', label: 'Exam Name', type: 'text' },
      { name: 'marks', label: 'Marks', type: 'number' },
      { name: 'grade', label: 'Grade', type: 'text' },
    ],
    columns: ['studentId', 'subjectId', 'examName', 'marks', 'grade'],
  },
  {
    key: 'fees',
    title: 'Fees',
    icon: 'fees',
    endpoint: '/fees',
    listLabel: (row) => `Student #${row.studentId} — ${row.paymentStatus || ''}`,
    fields: [
      { name: 'studentId', label: 'Student ID', type: 'number', required: true },
      { name: 'amount', label: 'Total Amount', type: 'number' },
      { name: 'paidAmount', label: 'Paid Amount', type: 'number' },
      { name: 'dueAmount', label: 'Due Amount', type: 'number' },
      { name: 'paymentStatus', label: 'Payment Status', type: 'select', options: ['PAID', 'PARTIAL', 'UNPAID'] },
      { name: 'paymentDate', label: 'Payment Date', type: 'date' },
      { name: 'paymentMethod', label: 'Payment Method', type: 'text' },
    ],
    columns: ['studentId', 'amount', 'paidAmount', 'dueAmount', 'paymentStatus'],
  },
  {
    key: 'library-books',
    title: 'Library Books',
    icon: 'library',
    endpoint: '/library/books',
    listLabel: (row) => row.title,
    fields: [
      { name: 'bookCode', label: 'Book Code', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'quantity', label: 'Quantity', type: 'number' },
      { name: 'availableQuantity', label: 'Available Quantity', type: 'number' },
    ],
    columns: ['bookCode', 'title', 'author', 'category', 'quantity', 'availableQuantity'],
  },
  {
    key: 'book-issues',
    title: 'Book Issues',
    icon: 'bookIssues',
    endpoint: '/library/issues',
    listLabel: (row) => `Book #${row.bookId} → Student #${row.studentId}`,
    fields: [
      { name: 'bookId', label: 'Book ID', type: 'number', required: true },
      { name: 'studentId', label: 'Student ID', type: 'number', required: true },
      { name: 'issueDate', label: 'Issue Date', type: 'date' },
      { name: 'returnDate', label: 'Return Date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['ISSUED', 'RETURNED'] },
    ],
    columns: ['bookId', 'studentId', 'issueDate', 'returnDate', 'status'],
  },
  {
    key: 'notices',
    title: 'Notices',
    icon: 'notices',
    endpoint: '/notices',
    listLabel: (row) => row.title,
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'message', label: 'Message', type: 'textarea' },
      { name: 'createdDate', label: 'Created Date', type: 'date' },
      { name: 'targetAudience', label: 'Target Audience', type: 'select', options: ['ALL', 'STUDENTS', 'TEACHERS', 'PARENTS'] },
    ],
    columns: ['title', 'targetAudience', 'createdDate'],
  },
  {
    key: 'transport',
    title: 'Transport',
    icon: 'transport',
    endpoint: '/transport',
    listLabel: (row) => row.vehicleNumber,
    fields: [
      { name: 'vehicleNumber', label: 'Vehicle Number', type: 'text', required: true },
      { name: 'routeName', label: 'Route Name', type: 'text' },
      { name: 'driverName', label: 'Driver Name', type: 'text' },
      { name: 'driverPhone', label: 'Driver Phone', type: 'text' },
      { name: 'pickupPoint', label: 'Pickup Point', type: 'text' },
    ],
    columns: ['vehicleNumber', 'routeName', 'driverName', 'driverPhone', 'pickupPoint'],
  },
  {
    key: 'hostel',
    title: 'Hostel',
    icon: 'hostel',
    endpoint: '/hostel',
    listLabel: (row) => `${row.hostelName || ''} — Room ${row.roomNumber || ''}`,
    fields: [
      { name: 'hostelName', label: 'Hostel Name', type: 'text', required: true },
      { name: 'roomNumber', label: 'Room Number', type: 'text' },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'occupied', label: 'Occupied', type: 'number' },
      { name: 'studentId', label: 'Student ID', type: 'number' },
    ],
    columns: ['hostelName', 'roomNumber', 'capacity', 'occupied', 'studentId'],
  },
]

export const getModule = (key) => modules.find((m) => m.key === key)
